spring.application.name=formularios-encadenadosBBDD
spring.datasource.url=jdbc:mysql://localhost:3306/dwes8

spring.datasource.username=daw2
spring.datasource.password=LaElipa
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update